### ISSUE TITLE
有办法使用动态编译的VIEWS了吗？

### ISSUE THREAD

**Issue by j4587698** [lamondlu/Mystique#15]
找了好多资料，实在是没发现有啥好办法，动态编译说AddRazorRuntimeCompilation里加路径，也不管用。

**Comment by lamondlu** [comment]
我觉得你说的是预编译Views, 动态编译的Views本来就可以使用, 预编译Views现在还没有找到什么方案

**Comment by j4587698** [comment]
@lamondlu 是的，就是预编译的views，在setup挂进去就好使，中间挂进去就报错，也是奇了怪了。看源码也没找到啥地方做了特殊处理

**Comment by j4587698** [comment]
翻了一下源码，大概知道为什么了，但是感觉不好改。。。。

**Comment by j4587698** [comment]
@lamondlu 找到一个办法。。有点low，不过貌似能实现了，我上传了一个测试工程,RCLTest，用的RazorPage，应该View也是一样的。

**Comment by j4587698** [comment]
动态编译的那种需要的东西更多。。。烦得要死啊。

**Comment by lamondlu** [comment]
慢慢来，问题要一个一个解决。
我还在看源码，主要有一个问题没想明白
如果在启动时加载预编译View就没有问题（参见之前博客第一章），运行时加载预编译View就识别不了
我怀疑问题还是出在Checksum或者路由注册的问题上

**Comment by j4587698** [comment]
@lamondlu 不是的，其实是类似这样的代码.
```
            var feature = new ViewsFeature();
            applicationPartManager.PopulateFeature(feature);

            _compiler = new DefaultViewCompiler(feature.ViewDescriptors, loggerFactory.CreateLogger<DefaultViewCompiler>());
```
这段代码在DefaultViewCompilerProvider中，然后以单例的模式注入进去。
feature.ViewDescriptor是整个PartManager的所有.views.dll，在ViewCompiler里面会先去查找feature.ViewDescriptor中有没有对应的内容，如果有，就直接返回了，这个时候不报错。如果没有就会继续往下找。
但是当DefaultViewCompilerProvider（如果有运行时编译是调用RuntimeViewCompilerProvider）实例化以后，我们在PartManager中虽然加入了新的feature.ViewDescriptor，但是并没有同步到DefaultViewCompilerProvider中，所以依旧找不到，就会报错了。
我在我的RCLTest中重写了DefaultViewCompilerProvider，然后加一个modify方法，当修改的时候重新生成一个ViewCompiler，就可以显示。
这里已经搞定了。但是如果使用了运行时编译，RuntimeViewCompilerProvider里面的RuntimeViewCompiler套了好多层internal的类，几乎没办法重写了。

**Comment by j4587698** [comment]
提了个issue希望asp.net core能把ViewCompiler变成public，结果被拒了。说不在计划中，那就没啥好办法了，不用编译cshtml的话很简单，用的话就没辙了，只能尝试重写所有的编译

**Comment by mindfocus** [comment]
请问整个讨论还是基于 .NET Core 3.1 么？还是准备用5了？

**Comment by j4587698** [comment]
@mindfocus 都一样，这一块3.1跟5没有变化。同样的代码都适用，反正修改申请被拒了

**Comment by lamondlu** [comment]
动态加载预编译视图的问题，已经能解决了，可以参考.NET 5分支的实现，中间借用了你前面的代码
近几天会更新第九章的博客

**Comment by lamondlu** [comment]
> 请问整个讨论还是基于 .NET Core 3.1 么？还是准备用5了？

项目已经升级到.NET 5

**Comment by j4587698** [comment]
@lamondlu 连同动态编译cshtml那边一起吗？还是只能选一个？动态加载那边其实我早就做出来了，上面那个RCLTest就是可以动态加载的。但是动态加载就不能调用动态编译，不然我这边就炸了。挠头的是这个。

**Comment by lamondlu** [comment]
@j4587698 可以直接使用插件预编译的views.dll, 不再需要运行时编译了

**Comment by j4587698** [comment]
@lamondlu 嗯，暂时只能这么玩，RuntimeViewCompilerProvider套的层数实在太多了，本来我想搞它，结果发现重写能把自己玩死。提了个issues希望asp.net core把RuntimeViewCompiler改成public的被拒绝了。

**Comment by lamondlu** [comment]
博客已更新：https://www.cnblogs.com/lwqlun/p/13992077.html
