### ISSUE TITLE
更新支持net5

### ISSUE THREAD

**Issue by ghd258** [lamondlu/Mystique#16]
更新支持net5

**Comment by lamondlu** [comment]
好的，周末升级一下，看看

**Comment by lamondlu** [comment]
已升级到5.0，demo程序运行正常

**Comment by lamondlu** [comment]
后续我再试试，升级到5.0之后，运行时编译的问题是否解决

**Comment by ghd258** [comment]
https://github.com/aspnet/AspNetCore/issues/13312  这个问题解决了吗

**Comment by ghd258** [comment]
https://www.cnblogs.com/lwqlun/p/11395828.html   这段意思是说ASP.NET Core暂时不支持动态加载程序集，如果要在当前版本实现功能，需要自己实现一个AssemblyPart类， 在获取程序集路径的时候，返回空集合而不是空字符串。

**Comment by lamondlu** [comment]
@ghd258 这个已经修复了
