### ISSUE TITLE
update net core 3.0

### ISSUE THREAD

**Issue by ghd258** [lamondlu/Mystique#2]
update net core 3.0

**Comment by lamondlu** [comment]
我周末升级一下看看

**Comment by lamondlu** [comment]
@ghd258 已经升级了，代码没变动，只是升级的Nuget包

**Comment by ghd258** [comment]
厉害 我也是升级了nuget包  编译报错很多啊

**Comment by ghd258** [comment]
![QQ图片20191010093119](https://user-images.githubusercontent.com/4811375/66532117-cc53f780-eb40-11e9-8ceb-2f42a434880a.png)
下载你最想的还是这么多错误 ，你本地是不是直接引用本地目录的dll什么的了

**Comment by ghd258** [comment]
我已经处理了 可以加qq 14983030 交个朋友  我把代码给您
