### ISSUE TITLE
InvalidOperationException: The view 'HelloWorld' was not found.

### ISSUE THREAD

**Issue by QJesus** [lamondlu/Mystique#3]
![image](https://user-images.githubusercontent.com/9971413/66725653-c757b680-ee66-11e9-9b75-69f9bb29a15e.png)

![image](https://user-images.githubusercontent.com/9971413/66725661-d474a580-ee66-11e9-9c79-83823f6c20b6.png)

**Comment by lamondlu** [comment]
Hi, 
你这个是在Visual Studio中使用调试模式启动项目的么？
在VS调试模式中，会出现这个问题，暂时只能将项目发布之后，使用dotnet命令启动

晚上我研究一下这个问题。

**Comment by lamondlu** [comment]
![image](https://user-images.githubusercontent.com/11512490/66731607-d3556f80-ee8a-11e9-9300-60570540b81a.png)
![image](https://user-images.githubusercontent.com/11512490/66731629-e49e7c00-ee8a-11e9-823b-50467f1516d8.png)

**Comment by lamondlu** [comment]
这里的主要问题是代码中，我使用了AppDomain.CurrentDomain.BaseDirectory来定位插件
![image](https://user-images.githubusercontent.com/11512490/66731981-a904b180-ee8c-11e9-9f6c-4e9a9861c43e.png)
如果是调试模式启动，启动目录会有区别

**Comment by lamondlu** [comment]
这个问题的解决方式是，在Visual Studio中将当前项目的启动目录标记为bin目录即可，后续会在第七篇中更新
